version: "3"
services:
  docs_sphinx:
    build:
      context: .
      dockerfile: docs/Dockerfile
      args:
        ENV: ${ENV}
    image: broker_docs_sphinx
    volumes:
      - ./docs:/docs
    command: make html
  docs_asyncapi:
    image: asyncapi/generator:1.15.5
    volumes:
      - ./docs:/docs
      - ./docs/api.yml:/app/api.yml
      - ./docs/html:/app/output
    command: --force-write -o ./output api.yml @asyncapi/html-template
  broker_bash:
    image: broker_image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    command: bash
  broker:
    image: broker_image
    links:
      - redis
      - arangodb
    depends_on:
      - redis
      - arangodb
      - broker_bash
    command: python3 broker/app.py
    expose:
      - ${BROKER_PORT}
    ports:
      - ${BROKER_PORT}:${BROKER_PORT}
    restart: unless-stopped
  guard:
    image: broker_image
    links:
      - broker
      - redis
    depends_on:
      - broker
      - redis
      - broker_bash
    command: python3 main.py
  redis:
    image: redis
    restart: unless-stopped
  arangodb:
    image: arangodb/arangodb:3.10.9
    expose:
      - "8529"
    restart: unless-stopped
    healthcheck:
      test: arangosh --server.endpoint tcp://localhost:8529 | grep -q 'for a tutorial' || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGODB_ROOT_PASSWORD}
      - ARANGO_NO_AUTH=1