name: nlp_api
channels:
  - defaults
dependencies:
  - python==3.10.8
  - pip>=22.1.2
  - tqdm>=4.62.3
  - matplotlib>=3.4.3
  - pandas>=1.3.4
  - jupyter>=1.0.0
  - numpy>=1.23.1
  - pip:
    - docker>=6.1.3
    - -r ./requirements.txt