name: fill_mask
description: Fill the mask token with a word
pipeline:
  task: fill-mask
  model: bert-base-uncased
input:
  data:
    text:
      type: string
      required: true
      description: The text to be classified
  example: {text: "This is a simple [MASK]."}
output:
  data:
    type: array
    description: List of results
    items:
      score:
        type: float
        description: The score of the classification
      token:
        type: integer
        description: Token ID of the masked word
      token_str:
        type: string
        description: Token string of the masked word
      sequence:
        type: string
        description: The sequence with the masked word replaced
  example: [{'score': 0.042, 'token': 3291, 'token_str': 'problem', 'sequence': 'this is a simple problem.'}, {'score': 0.031, 'token': 3160, 'token_str': 'question', 'sequence': 'this is a simple question.'}, {'score': 0.03, 'token': 8522, 'token_str': 'equation', 'sequence': 'this is a simple equation.'}, {'score': 0.027, 'token': 2028, 'token_str': 'one', 'sequence': 'this is a simple one.'}, {'score': 0.024, 'token': 3627, 'token_str': 'rule', 'sequence': 'this is a simple rule.'}]