name: summarization
description: Summarize a text
pipeline:
  task: summarization
  model: t5-base
  tokenizer: t5-base
  framework: tf
input:
  data:
    text:
      type: string
      required: true
      description: The question to answer
    min_length:
      type: integer
      required: true
      description: The minimum length of the summary
    max_length:
      type: integer
      required: true
      description: The maximum length of the summary
  example: {"An apple a day, keeps the doctor away", min_length=5, max_length=20}
output:
  data:
    summarization:
      type: string
      description: Summarization
  example: {'summarization': '...'}